version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: cote-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: cote-redis
    restart: always
    ports:
      - "6379:6379"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cote-spring
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

volumes:
  mongo_data: