spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      host: cote-redis
      port: 6379
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cors:
  allowed-origins: http://localhost:3000,${PROD_ORIGIN}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG