spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG