name: Deploy Spring Boot to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # merge된 경우에만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Replace environment variables in application-prod.yml
        run: |
          envsubst < ./src/main/resources/application-prod.yml > ./src/main/resources/application-prod.yml.tmp
          mv ./src/main/resources/application-prod.yml.tmp ./src/main/resources/application-prod.yml
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
          PROD_ORIGIN: ${{ secrets.PROD_ORIGIN }}

      - name: Build Spring Boot JAR (skip tests)
        run: ./gradlew clean build -x test

      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."  # 전체 프로젝트 복사
          target: "~/cote-house/backend"

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/cote-house/backend

            echo "✅ Starting deployment with Docker Compose"
            docker compose down
            docker image prune -f
            docker volume prune -f
            docker compose up -d --build